spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa3dbfyw6RAFf24n4x6
            client-secret: 6GQyWRprEnHqbEOL1e3I7D3YehK6x2Ewq1yG6FDT
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-523074.okta.com/oauth2/default