export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOAD_PROFILE = 'LOAD_PROFILE'

export const SET_GROUPS = 'SET_GROUPS'
export const SHOW_MODAL = 'SHOW_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const REQUEST_START = 'REQUEST_START'
export const REQUEST_COMPLETE = 'REQUEST_COMPLETE'